### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by Ludwigvsch** [Ludwigvsch/Jahresnote#3]
Traceback (most recent call last):
  File "/Users/user/github/Jahresnote/Erste_Abfrage.py", line 92, in <module>
    print(test_Halbjahre.Test_finish())
  File "/Users/user/github/Jahresnote/Erste_Abfrage.py", line 89, in Test_finish
    self.Speichern_in_Datenbanken()
  File "/Users/user/github/Jahresnote/Erste_Abfrage.py", line 34, in Speichern_in_Datenbanken
    (self.Fachname, self.Schulaufgabe_Hauptfach, self.EX1_Hauptfach, self.EX2_Hauptfach, self.Muendliche_Note_Hauptfach, self.Kurzarbeit_Hauptfach))
sqlite3.OperationalError: database is locked

**Comment by Ludwigvsch** [comment]
I didn't great an object the right why
